name = "seen"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-26"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "SEEN_DB"
database_name = "seen"
database_id = "a221f142-b966-4f92-98fa-ff9739f4d2fd"

[observability]
enabled = true
head_sampling_rate = 1


[[r2_buckets]]
binding = "SEEN_BUCKET"
bucket_name = "seen"

[[vectorize]]
binding = "VECTORIZE"
index_name = "seen-index"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SEEN_KV"
id = "a86e7def7d384342bcd7b1c490a3bfbd"
